name: CI/CD Pipeline for GCP

on: push

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-1    # TODO: update to cluster name
  GKE_ZONE: us-central1-c   # TODO: update to cluster zone
  DEPLOYMENT_NAME: gke-test # TODO: update to deployment name
  IMAGE: static-site

jobs:
  build:
    name: build + publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
  deploy-dev:
    needs: build
    name: deploy to dev
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    environment: dev
    
    steps:
    - name: deploy
      run: echo 'placeholder'
      
  deploy-test:
    needs: deploy-dev
    name: deploy to test
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    environment: test
    
    steps:
    - name: deploy
      run: echo 'placeholder'
      
  deploy-prod:
    needs: deploy-test
    name: deploy to prod
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    environment: prod
    
    steps:
    - name: deploy
      run: echo 'placeholder'
